/**
 * websocket-gateway
 * Describe the weboscket endpoints
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CertificateStatusDto from './CertificateStatusDto';
import PodStatusDto from './PodStatusDto';
import ServiceStateDto from './ServiceStateDto';

/**
 * The ApplicationStatusDto model module.
 * @module model/ApplicationStatusDto
 * @version $(grep &#39;version&#39; _build/openapi.yaml | head -1 | tr &#39;:&#39; &#39;\n&#39; | tail -1 | tr -d &#39; &#39;)
 */
class ApplicationStatusDto {
    /**
     * Constructs a new <code>ApplicationStatusDto</code>.
     * @alias module:model/ApplicationStatusDto
     * @param certificates {Array.<module:model/CertificateStatusDto>} 
     * @param id {String} 
     * @param pods {Array.<module:model/PodStatusDto>} 
     * @param state {module:model/ServiceStateDto} 
     */
    constructor(certificates, id, pods, state) { 
        
        ApplicationStatusDto.initialize(this, certificates, id, pods, state);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, certificates, id, pods, state) { 
        obj['certificates'] = certificates;
        obj['id'] = id;
        obj['pods'] = pods;
        obj['state'] = state;
    }

    /**
     * Constructs a <code>ApplicationStatusDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApplicationStatusDto} obj Optional instance to populate.
     * @return {module:model/ApplicationStatusDto} The populated <code>ApplicationStatusDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApplicationStatusDto();

            if (data.hasOwnProperty('certificates')) {
                obj['certificates'] = ApiClient.convertToType(data['certificates'], [CertificateStatusDto]);
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('pods')) {
                obj['pods'] = ApiClient.convertToType(data['pods'], [PodStatusDto]);
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ServiceStateDto.constructFromObject(data['state']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/CertificateStatusDto>} certificates
 */
ApplicationStatusDto.prototype['certificates'] = undefined;

/**
 * @member {String} id
 */
ApplicationStatusDto.prototype['id'] = undefined;

/**
 * @member {Array.<module:model/PodStatusDto>} pods
 */
ApplicationStatusDto.prototype['pods'] = undefined;

/**
 * @member {module:model/ServiceStateDto} state
 */
ApplicationStatusDto.prototype['state'] = undefined;






export default ApplicationStatusDto;

