/**
 * websocket-gateway
 * Describe the weboscket endpoints
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ClusterNodeDto from './ClusterNodeDto';

/**
 * The ClusterStatusDto model module.
 * @module model/ClusterStatusDto
 * @version $(grep &#39;version&#39; _build/openapi.yaml | head -1 | tr &#39;:&#39; &#39;\n&#39; | tail -1 | tr -d &#39; &#39;)
 */
class ClusterStatusDto {
    /**
     * Constructs a new <code>ClusterStatusDto</code>.
     * @alias module:model/ClusterStatusDto
     * @param nodes {Array.<module:model/ClusterNodeDto>} 
     */
    constructor(nodes) { 
        
        ClusterStatusDto.initialize(this, nodes);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, nodes) { 
        obj['nodes'] = nodes;
    }

    /**
     * Constructs a <code>ClusterStatusDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ClusterStatusDto} obj Optional instance to populate.
     * @return {module:model/ClusterStatusDto} The populated <code>ClusterStatusDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ClusterStatusDto();

            if (data.hasOwnProperty('nodes')) {
                obj['nodes'] = ApiClient.convertToType(data['nodes'], [ClusterNodeDto]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/ClusterNodeDto>} nodes
 */
ClusterStatusDto.prototype['nodes'] = undefined;






export default ClusterStatusDto;

