/**
 * websocket-gateway
 * Describe the weboscket endpoints
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ContainerStateDto from './ContainerStateDto';
import ContainerStateTerminatedDto from './ContainerStateTerminatedDto';

/**
 * The ContainerStatusDto model module.
 * @module model/ContainerStatusDto
 * @version $(grep &#39;version&#39; _build/openapi.yaml | head -1 | tr &#39;:&#39; &#39;\n&#39; | tail -1 | tr -d &#39; &#39;)
 */
class ContainerStatusDto {
    /**
     * Constructs a new <code>ContainerStatusDto</code>.
     * @alias module:model/ContainerStatusDto
     * @param image {String} 
     * @param name {String} 
     * @param restartCount {Number} 
     */
    constructor(image, name, restartCount) { 
        
        ContainerStatusDto.initialize(this, image, name, restartCount);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, image, name, restartCount) { 
        obj['image'] = image;
        obj['name'] = name;
        obj['restart_count'] = restartCount;
    }

    /**
     * Constructs a <code>ContainerStatusDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ContainerStatusDto} obj Optional instance to populate.
     * @return {module:model/ContainerStatusDto} The populated <code>ContainerStatusDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContainerStatusDto();

            if (data.hasOwnProperty('current_state')) {
                obj['current_state'] = ApiClient.convertToType(data['current_state'], ContainerStateDto);
            }
            if (data.hasOwnProperty('image')) {
                obj['image'] = ApiClient.convertToType(data['image'], 'String');
            }
            if (data.hasOwnProperty('last_terminated_state')) {
                obj['last_terminated_state'] = ApiClient.convertToType(data['last_terminated_state'], ContainerStateTerminatedDto);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('restart_count')) {
                obj['restart_count'] = ApiClient.convertToType(data['restart_count'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ContainerStatusDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ContainerStatusDto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ContainerStatusDto.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `current_state`
        if (data['current_state']) { // data not null
          ContainerStateDto.validateJSON(data['current_state']);
        }
        // ensure the json data is a string
        if (data['image'] && !(typeof data['image'] === 'string' || data['image'] instanceof String)) {
            throw new Error("Expected the field `image` to be a primitive type in the JSON string but got " + data['image']);
        }
        // validate the optional field `last_terminated_state`
        if (data['last_terminated_state']) { // data not null
          ContainerStateTerminatedDto.validateJSON(data['last_terminated_state']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}

ContainerStatusDto.RequiredProperties = ["image", "name", "restart_count"];

/**
 * @member {module:model/ContainerStateDto} current_state
 */
ContainerStatusDto.prototype['current_state'] = undefined;

/**
 * @member {String} image
 */
ContainerStatusDto.prototype['image'] = undefined;

/**
 * @member {module:model/ContainerStateTerminatedDto} last_terminated_state
 */
ContainerStatusDto.prototype['last_terminated_state'] = undefined;

/**
 * @member {String} name
 */
ContainerStatusDto.prototype['name'] = undefined;

/**
 * @member {Number} restart_count
 */
ContainerStatusDto.prototype['restart_count'] = undefined;






export default ContainerStatusDto;

