/**
 * websocket-gateway
 * Describe the weboscket endpoints
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ContainerStateTerminatedDto model module.
 * @module model/ContainerStateTerminatedDto
 * @version $(grep &#39;version&#39; _build/openapi.yaml | head -1 | tr &#39;:&#39; &#39;\n&#39; | tail -1 | tr -d &#39; &#39;)
 */
class ContainerStateTerminatedDto {
    /**
     * Constructs a new <code>ContainerStateTerminatedDto</code>.
     * @alias module:model/ContainerStateTerminatedDto
     * @param exitCode {Number} 
     * @param exitCodeMessage {String} 
     * @param message {String} 
     * @param reason {String} 
     * @param signal {Number} 
     */
    constructor(exitCode, exitCodeMessage, message, reason, signal) { 
        
        ContainerStateTerminatedDto.initialize(this, exitCode, exitCodeMessage, message, reason, signal);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, exitCode, exitCodeMessage, message, reason, signal) { 
        obj['exit_code'] = exitCode;
        obj['exit_code_message'] = exitCodeMessage;
        obj['message'] = message;
        obj['reason'] = reason;
        obj['signal'] = signal;
    }

    /**
     * Constructs a <code>ContainerStateTerminatedDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ContainerStateTerminatedDto} obj Optional instance to populate.
     * @return {module:model/ContainerStateTerminatedDto} The populated <code>ContainerStateTerminatedDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContainerStateTerminatedDto();

            if (data.hasOwnProperty('exit_code')) {
                obj['exit_code'] = ApiClient.convertToType(data['exit_code'], 'Number');
            }
            if (data.hasOwnProperty('exit_code_message')) {
                obj['exit_code_message'] = ApiClient.convertToType(data['exit_code_message'], 'String');
            }
            if (data.hasOwnProperty('finished_at')) {
                obj['finished_at'] = ApiClient.convertToType(data['finished_at'], 'Number');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('reason')) {
                obj['reason'] = ApiClient.convertToType(data['reason'], 'String');
            }
            if (data.hasOwnProperty('signal')) {
                obj['signal'] = ApiClient.convertToType(data['signal'], 'Number');
            }
            if (data.hasOwnProperty('started_at')) {
                obj['started_at'] = ApiClient.convertToType(data['started_at'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} exit_code
 */
ContainerStateTerminatedDto.prototype['exit_code'] = undefined;

/**
 * @member {String} exit_code_message
 */
ContainerStateTerminatedDto.prototype['exit_code_message'] = undefined;

/**
 * @member {Number} finished_at
 */
ContainerStateTerminatedDto.prototype['finished_at'] = undefined;

/**
 * @member {String} message
 */
ContainerStateTerminatedDto.prototype['message'] = undefined;

/**
 * @member {String} reason
 */
ContainerStateTerminatedDto.prototype['reason'] = undefined;

/**
 * @member {Number} signal
 */
ContainerStateTerminatedDto.prototype['signal'] = undefined;

/**
 * @member {Number} started_at
 */
ContainerStateTerminatedDto.prototype['started_at'] = undefined;






export default ContainerStateTerminatedDto;

