/**
 * websocket-gateway
 * Describe the weboscket endpoints
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ServiceStateDto from './ServiceStateDto';

/**
 * The ContainerStateDto model module.
 * @module model/ContainerStateDto
 * @version $(grep &#39;version&#39; _build/openapi.yaml | head -1 | tr &#39;:&#39; &#39;\n&#39; | tail -1 | tr -d &#39; &#39;)
 */
class ContainerStateDto {
    /**
     * Constructs a new <code>ContainerStateDto</code>.
     * @alias module:model/ContainerStateDto
     * @param state {module:model/ServiceStateDto} 
     */
    constructor(state) { 
        
        ContainerStateDto.initialize(this, state);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, state) { 
        obj['state'] = state;
    }

    /**
     * Constructs a <code>ContainerStateDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ContainerStateDto} obj Optional instance to populate.
     * @return {module:model/ContainerStateDto} The populated <code>ContainerStateDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContainerStateDto();

            if (data.hasOwnProperty('started_at')) {
                obj['started_at'] = ApiClient.convertToType(data['started_at'], 'Number');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ServiceStateDto.constructFromObject(data['state']);
            }
            if (data.hasOwnProperty('state_message')) {
                obj['state_message'] = ApiClient.convertToType(data['state_message'], 'String');
            }
            if (data.hasOwnProperty('state_reason')) {
                obj['state_reason'] = ApiClient.convertToType(data['state_reason'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} started_at
 */
ContainerStateDto.prototype['started_at'] = undefined;

/**
 * @member {module:model/ServiceStateDto} state
 */
ContainerStateDto.prototype['state'] = undefined;

/**
 * @member {String} state_message
 */
ContainerStateDto.prototype['state_message'] = undefined;

/**
 * @member {String} state_reason
 */
ContainerStateDto.prototype['state_reason'] = undefined;






export default ContainerStateDto;

