/**
 * websocket-gateway
 * Describe the weboscket endpoints
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NodeResourceDto model module.
 * @module model/NodeResourceDto
 * @version $(grep &#39;version&#39; _build/openapi.yaml | head -1 | tr &#39;:&#39; &#39;\n&#39; | tail -1 | tr -d &#39; &#39;)
 */
class NodeResourceDto {
    /**
     * Constructs a new <code>NodeResourceDto</code>.
     * @alias module:model/NodeResourceDto
     * @param cpuMilli {Number} 
     * @param ephemeralStorageGib {Number} 
     * @param memoryMib {Number} 
     * @param pods {Number} 
     */
    constructor(cpuMilli, ephemeralStorageGib, memoryMib, pods) { 
        
        NodeResourceDto.initialize(this, cpuMilli, ephemeralStorageGib, memoryMib, pods);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, cpuMilli, ephemeralStorageGib, memoryMib, pods) { 
        obj['cpu_milli'] = cpuMilli;
        obj['ephemeral_storage_gib'] = ephemeralStorageGib;
        obj['memory_mib'] = memoryMib;
        obj['pods'] = pods;
    }

    /**
     * Constructs a <code>NodeResourceDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NodeResourceDto} obj Optional instance to populate.
     * @return {module:model/NodeResourceDto} The populated <code>NodeResourceDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NodeResourceDto();

            if (data.hasOwnProperty('cpu_milli')) {
                obj['cpu_milli'] = ApiClient.convertToType(data['cpu_milli'], 'Number');
            }
            if (data.hasOwnProperty('ephemeral_storage_gib')) {
                obj['ephemeral_storage_gib'] = ApiClient.convertToType(data['ephemeral_storage_gib'], 'Number');
            }
            if (data.hasOwnProperty('memory_mib')) {
                obj['memory_mib'] = ApiClient.convertToType(data['memory_mib'], 'Number');
            }
            if (data.hasOwnProperty('pods')) {
                obj['pods'] = ApiClient.convertToType(data['pods'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} cpu_milli
 */
NodeResourceDto.prototype['cpu_milli'] = undefined;

/**
 * @member {Number} ephemeral_storage_gib
 */
NodeResourceDto.prototype['ephemeral_storage_gib'] = undefined;

/**
 * @member {Number} memory_mib
 */
NodeResourceDto.prototype['memory_mib'] = undefined;

/**
 * @member {Number} pods
 */
NodeResourceDto.prototype['pods'] = undefined;






export default NodeResourceDto;

