/**
 * websocket-gateway
 * Describe the weboscket endpoints
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProstTypesTimestamp from './ProstTypesTimestamp';

/**
 * The NodeConditionDto model module.
 * @module model/NodeConditionDto
 * @version $(grep &#39;version&#39; _build/openapi.yaml | head -1 | tr &#39;:&#39; &#39;\n&#39; | tail -1 | tr -d &#39; &#39;)
 */
class NodeConditionDto {
    /**
     * Constructs a new <code>NodeConditionDto</code>.
     * @alias module:model/NodeConditionDto
     * @param message {String} 
     * @param reason {String} 
     * @param status {String} 
     * @param type {String} 
     */
    constructor(message, reason, status, type) { 
        
        NodeConditionDto.initialize(this, message, reason, status, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, message, reason, status, type) { 
        obj['message'] = message;
        obj['reason'] = reason;
        obj['status'] = status;
        obj['type'] = type;
    }

    /**
     * Constructs a <code>NodeConditionDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NodeConditionDto} obj Optional instance to populate.
     * @return {module:model/NodeConditionDto} The populated <code>NodeConditionDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NodeConditionDto();

            if (data.hasOwnProperty('last_heartbeat_time')) {
                obj['last_heartbeat_time'] = ApiClient.convertToType(data['last_heartbeat_time'], ProstTypesTimestamp);
            }
            if (data.hasOwnProperty('last_transition_time')) {
                obj['last_transition_time'] = ApiClient.convertToType(data['last_transition_time'], ProstTypesTimestamp);
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('reason')) {
                obj['reason'] = ApiClient.convertToType(data['reason'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/ProstTypesTimestamp} last_heartbeat_time
 */
NodeConditionDto.prototype['last_heartbeat_time'] = undefined;

/**
 * @member {module:model/ProstTypesTimestamp} last_transition_time
 */
NodeConditionDto.prototype['last_transition_time'] = undefined;

/**
 * @member {String} message
 */
NodeConditionDto.prototype['message'] = undefined;

/**
 * @member {String} reason
 */
NodeConditionDto.prototype['reason'] = undefined;

/**
 * @member {String} status
 */
NodeConditionDto.prototype['status'] = undefined;

/**
 * @member {String} type
 */
NodeConditionDto.prototype['type'] = undefined;






export default NodeConditionDto;

