/**
 * websocket-gateway
 * Describe the weboscket endpoints
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PodDto from './PodDto';

/**
 * The ServiceListPodsResponseDto model module.
 * @module model/ServiceListPodsResponseDto
 * @version $(grep &#39;version&#39; _build/openapi.yaml | head -1 | tr &#39;:&#39; &#39;\n&#39; | tail -1 | tr -d &#39; &#39;)
 */
class ServiceListPodsResponseDto {
    /**
     * Constructs a new <code>ServiceListPodsResponseDto</code>.
     * @alias module:model/ServiceListPodsResponseDto
     * @param pods {Array.<module:model/PodDto>} 
     */
    constructor(pods) { 
        
        ServiceListPodsResponseDto.initialize(this, pods);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, pods) { 
        obj['pods'] = pods;
    }

    /**
     * Constructs a <code>ServiceListPodsResponseDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ServiceListPodsResponseDto} obj Optional instance to populate.
     * @return {module:model/ServiceListPodsResponseDto} The populated <code>ServiceListPodsResponseDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ServiceListPodsResponseDto();

            if (data.hasOwnProperty('pods')) {
                obj['pods'] = ApiClient.convertToType(data['pods'], [PodDto]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/PodDto>} pods
 */
ServiceListPodsResponseDto.prototype['pods'] = undefined;






export default ServiceListPodsResponseDto;

