/**
 * websocket-gateway
 * Describe the weboscket endpoints
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ServiceInfraLogResponseDto model module.
 * @module model/ServiceInfraLogResponseDto
 * @version $(grep &#39;version&#39; _build/openapi.yaml | head -1 | tr &#39;:&#39; &#39;\n&#39; | tail -1 | tr -d &#39; &#39;)
 */
class ServiceInfraLogResponseDto {
    /**
     * Constructs a new <code>ServiceInfraLogResponseDto</code>.
     * @alias module:model/ServiceInfraLogResponseDto
     * @param createdAt {Number} Unix timestamp with millisecond precision
     * @param message {String} 
     */
    constructor(createdAt, message) { 
        
        ServiceInfraLogResponseDto.initialize(this, createdAt, message);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, createdAt, message) { 
        obj['created_at'] = createdAt;
        obj['message'] = message;
    }

    /**
     * Constructs a <code>ServiceInfraLogResponseDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ServiceInfraLogResponseDto} obj Optional instance to populate.
     * @return {module:model/ServiceInfraLogResponseDto} The populated <code>ServiceInfraLogResponseDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ServiceInfraLogResponseDto();

            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Number');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ServiceInfraLogResponseDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ServiceInfraLogResponseDto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ServiceInfraLogResponseDto.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }

        return true;
    }


}

ServiceInfraLogResponseDto.RequiredProperties = ["created_at", "message"];

/**
 * Unix timestamp with millisecond precision
 * @member {Number} created_at
 */
ServiceInfraLogResponseDto.prototype['created_at'] = undefined;

/**
 * @member {String} message
 */
ServiceInfraLogResponseDto.prototype['message'] = undefined;






export default ServiceInfraLogResponseDto;

