/**
 * websocket-gateway
 * Describe the weboscket endpoints
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MetricDto from './MetricDto';

/**
 * The ServiceMetricsDto model module.
 * @module model/ServiceMetricsDto
 * @version $(grep &#39;version&#39; _build/openapi.yaml | head -1 | tr &#39;:&#39; &#39;\n&#39; | tail -1 | tr -d &#39; &#39;)
 */
class ServiceMetricsDto {
    /**
     * Constructs a new <code>ServiceMetricsDto</code>.
     * @alias module:model/ServiceMetricsDto
     * @param cpu {module:model/MetricDto} 
     * @param memory {module:model/MetricDto} 
     * @param podName {String} 
     * @param storages {Array.<module:model/MetricDto>} 
     */
    constructor(cpu, memory, podName, storages) { 
        
        ServiceMetricsDto.initialize(this, cpu, memory, podName, storages);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, cpu, memory, podName, storages) { 
        obj['cpu'] = cpu;
        obj['memory'] = memory;
        obj['pod_name'] = podName;
        obj['storages'] = storages;
    }

    /**
     * Constructs a <code>ServiceMetricsDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ServiceMetricsDto} obj Optional instance to populate.
     * @return {module:model/ServiceMetricsDto} The populated <code>ServiceMetricsDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ServiceMetricsDto();

            if (data.hasOwnProperty('cpu')) {
                obj['cpu'] = MetricDto.constructFromObject(data['cpu']);
            }
            if (data.hasOwnProperty('memory')) {
                obj['memory'] = MetricDto.constructFromObject(data['memory']);
            }
            if (data.hasOwnProperty('pod_name')) {
                obj['pod_name'] = ApiClient.convertToType(data['pod_name'], 'String');
            }
            if (data.hasOwnProperty('storages')) {
                obj['storages'] = ApiClient.convertToType(data['storages'], [MetricDto]);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/MetricDto} cpu
 */
ServiceMetricsDto.prototype['cpu'] = undefined;

/**
 * @member {module:model/MetricDto} memory
 */
ServiceMetricsDto.prototype['memory'] = undefined;

/**
 * @member {String} pod_name
 */
ServiceMetricsDto.prototype['pod_name'] = undefined;

/**
 * @member {Array.<module:model/MetricDto>} storages
 */
ServiceMetricsDto.prototype['storages'] = undefined;






export default ServiceMetricsDto;

