/**
 * websocket-gateway
 * Describe the weboscket endpoints
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PodDto from './PodDto';

/**
 * The ServiceListPodsResponseDto model module.
 * @module model/ServiceListPodsResponseDto
 * @version $(grep &#39;version&#39; _build/openapi.yaml | head -1 | tr &#39;:&#39; &#39;\n&#39; | tail -1 | tr -d &#39; &#39;)
 */
class ServiceListPodsResponseDto {
    /**
     * Constructs a new <code>ServiceListPodsResponseDto</code>.
     * @alias module:model/ServiceListPodsResponseDto
     * @param pods {Array.<module:model/PodDto>} 
     */
    constructor(pods) { 
        
        ServiceListPodsResponseDto.initialize(this, pods);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, pods) { 
        obj['pods'] = pods;
    }

    /**
     * Constructs a <code>ServiceListPodsResponseDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ServiceListPodsResponseDto} obj Optional instance to populate.
     * @return {module:model/ServiceListPodsResponseDto} The populated <code>ServiceListPodsResponseDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ServiceListPodsResponseDto();

            if (data.hasOwnProperty('pods')) {
                obj['pods'] = ApiClient.convertToType(data['pods'], [PodDto]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ServiceListPodsResponseDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ServiceListPodsResponseDto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ServiceListPodsResponseDto.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['pods']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['pods'])) {
                throw new Error("Expected the field `pods` to be an array in the JSON data but got " + data['pods']);
            }
            // validate the optional field `pods` (array)
            for (const item of data['pods']) {
                PodDto.validateJSON(item);
            };
        }

        return true;
    }


}

ServiceListPodsResponseDto.RequiredProperties = ["pods"];

/**
 * @member {Array.<module:model/PodDto>} pods
 */
ServiceListPodsResponseDto.prototype['pods'] = undefined;






export default ServiceListPodsResponseDto;

