/**
 * websocket-gateway
 * Describe the weboscket endpoints
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ServiceLogResponseDto model module.
 * @module model/ServiceLogResponseDto
 * @version $(grep &#39;version&#39; _build/openapi.yaml | head -1 | tr &#39;:&#39; &#39;\n&#39; | tail -1 | tr -d &#39; &#39;)
 */
class ServiceLogResponseDto {
    /**
     * Constructs a new <code>ServiceLogResponseDto</code>.
     * @alias module:model/ServiceLogResponseDto
     * @param createdAt {Number} 
     * @param message {String} 
     * @param podName {String} 
     * @param version {String} 
     */
    constructor(createdAt, message, podName, version) { 
        
        ServiceLogResponseDto.initialize(this, createdAt, message, podName, version);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, createdAt, message, podName, version) { 
        obj['created_at'] = createdAt;
        obj['message'] = message;
        obj['pod_name'] = podName;
        obj['version'] = version;
    }

    /**
     * Constructs a <code>ServiceLogResponseDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ServiceLogResponseDto} obj Optional instance to populate.
     * @return {module:model/ServiceLogResponseDto} The populated <code>ServiceLogResponseDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ServiceLogResponseDto();

            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Number');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('pod_name')) {
                obj['pod_name'] = ApiClient.convertToType(data['pod_name'], 'String');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} created_at
 */
ServiceLogResponseDto.prototype['created_at'] = undefined;

/**
 * @member {String} message
 */
ServiceLogResponseDto.prototype['message'] = undefined;

/**
 * @member {String} pod_name
 */
ServiceLogResponseDto.prototype['pod_name'] = undefined;

/**
 * @member {String} version
 */
ServiceLogResponseDto.prototype['version'] = undefined;






export default ServiceLogResponseDto;

