/**
 * websocket-gateway
 * Describe the weboscket endpoints
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ClusterStatusDto from '../model/ClusterStatusDto';

/**
* ClusterStatus service.
* @module api/ClusterStatusApi
* @version $(grep 'version' _build/openapi.yaml | head -1 | tr ':' '\n' | tail -1 | tr -d ' ')
*/
export default class ClusterStatusApi {

    /**
    * Constructs a new ClusterStatusApi. 
    * @alias module:api/ClusterStatusApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the handleClusterStatusRequest operation.
     * @callback module:api/ClusterStatusApi~handleClusterStatusRequestCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ClusterStatusDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} organization 
     * @param {String} cluster 
     * @param {module:api/ClusterStatusApi~handleClusterStatusRequestCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ClusterStatusDto}
     */
    handleClusterStatusRequest(organization, cluster, callback) {
      let postBody = null;
      // verify the required parameter 'organization' is set
      if (organization === undefined || organization === null) {
        throw new Error("Missing the required parameter 'organization' when calling handleClusterStatusRequest");
      }
      // verify the required parameter 'cluster' is set
      if (cluster === undefined || cluster === null) {
        throw new Error("Missing the required parameter 'cluster' when calling handleClusterStatusRequest");
      }

      let pathParams = {
        'organization': organization,
        'cluster': cluster
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ClusterStatusDto;
      return this.apiClient.callApi(
        '/cluster/status', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
