/**
 * websocket-gateway
 * Describe the weboscket endpoints
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ServiceMetricsDto from '../model/ServiceMetricsDto';
import ServiceType from '../model/ServiceType';

/**
* ServiceMetrics service.
* @module api/ServiceMetricsApi
* @version $(grep 'version' _build/openapi.yaml | head -1 | tr ':' '\n' | tail -1 | tr -d ' ')
*/
export default class ServiceMetricsApi {

    /**
    * Constructs a new ServiceMetricsApi. 
    * @alias module:api/ServiceMetricsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the handleMetricsRequest operation.
     * @callback module:api/ServiceMetricsApi~handleMetricsRequestCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ServiceMetricsDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} organization 
     * @param {String} cluster 
     * @param {String} project 
     * @param {String} environment 
     * @param {String} service 
     * @param {module:model/ServiceType} serviceType 
     * @param {module:api/ServiceMetricsApi~handleMetricsRequestCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ServiceMetricsDto}
     */
    handleMetricsRequest(organization, cluster, project, environment, service, serviceType, callback) {
      let postBody = null;
      // verify the required parameter 'organization' is set
      if (organization === undefined || organization === null) {
        throw new Error("Missing the required parameter 'organization' when calling handleMetricsRequest");
      }
      // verify the required parameter 'cluster' is set
      if (cluster === undefined || cluster === null) {
        throw new Error("Missing the required parameter 'cluster' when calling handleMetricsRequest");
      }
      // verify the required parameter 'project' is set
      if (project === undefined || project === null) {
        throw new Error("Missing the required parameter 'project' when calling handleMetricsRequest");
      }
      // verify the required parameter 'environment' is set
      if (environment === undefined || environment === null) {
        throw new Error("Missing the required parameter 'environment' when calling handleMetricsRequest");
      }
      // verify the required parameter 'service' is set
      if (service === undefined || service === null) {
        throw new Error("Missing the required parameter 'service' when calling handleMetricsRequest");
      }
      // verify the required parameter 'serviceType' is set
      if (serviceType === undefined || serviceType === null) {
        throw new Error("Missing the required parameter 'serviceType' when calling handleMetricsRequest");
      }

      let pathParams = {
        'organization': organization,
        'cluster': cluster,
        'project': project,
        'environment': environment,
        'service': service,
        'service_type': serviceType
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ServiceMetricsDto;
      return this.apiClient.callApi(
        '/service/metrics', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
