/**
 * websocket-gateway
 * Describe the weboscket endpoints
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ServiceStatusDto from '../model/ServiceStatusDto';

/**
* ServiceStatus service.
* @module api/ServiceStatusApi
* @version $(grep 'version' _build/openapi.yaml | head -1 | tr ':' '\n' | tail -1 | tr -d ' ')
*/
export default class ServiceStatusApi {

    /**
    * Constructs a new ServiceStatusApi. 
    * @alias module:api/ServiceStatusApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the handleServiceStatusRequest operation.
     * @callback module:api/ServiceStatusApi~handleServiceStatusRequestCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ServiceStatusDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} organization 
     * @param {String} cluster 
     * @param {String} project 
     * @param {String} environment 
     * @param {module:api/ServiceStatusApi~handleServiceStatusRequestCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ServiceStatusDto}
     */
    handleServiceStatusRequest(organization, cluster, project, environment, callback) {
      let postBody = null;
      // verify the required parameter 'organization' is set
      if (organization === undefined || organization === null) {
        throw new Error("Missing the required parameter 'organization' when calling handleServiceStatusRequest");
      }
      // verify the required parameter 'cluster' is set
      if (cluster === undefined || cluster === null) {
        throw new Error("Missing the required parameter 'cluster' when calling handleServiceStatusRequest");
      }
      // verify the required parameter 'project' is set
      if (project === undefined || project === null) {
        throw new Error("Missing the required parameter 'project' when calling handleServiceStatusRequest");
      }
      // verify the required parameter 'environment' is set
      if (environment === undefined || environment === null) {
        throw new Error("Missing the required parameter 'environment' when calling handleServiceStatusRequest");
      }

      let pathParams = {
        'organization': organization,
        'cluster': cluster,
        'project': project,
        'environment': environment
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ServiceStatusDto;
      return this.apiClient.callApi(
        '/service/status', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
