/**
 * websocket-gateway
 * Describe the weboscket endpoints
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WebsocketGateway);
  }
}(this, function(expect, WebsocketGateway) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WebsocketGateway.CertificateStatusDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CertificateStatusDto', function() {
    it('should create an instance of CertificateStatusDto', function() {
      // uncomment below and update the code to test CertificateStatusDto
      //var instance = new WebsocketGateway.CertificateStatusDto();
      //expect(instance).to.be.a(WebsocketGateway.CertificateStatusDto);
    });

    it('should have the property dnsNames (base name: "dns_names")', function() {
      // uncomment below and update the code to test the property dnsNames
      //var instance = new WebsocketGateway.CertificateStatusDto();
      //expect(instance).to.be();
    });

    it('should have the property failedIssuanceAttemptCount (base name: "failed_issuance_attempt_count")', function() {
      // uncomment below and update the code to test the property failedIssuanceAttemptCount
      //var instance = new WebsocketGateway.CertificateStatusDto();
      //expect(instance).to.be();
    });

    it('should have the property lastFailureIssuanceTime (base name: "last_failure_issuance_time")', function() {
      // uncomment below and update the code to test the property lastFailureIssuanceTime
      //var instance = new WebsocketGateway.CertificateStatusDto();
      //expect(instance).to.be();
    });

    it('should have the property notAfter (base name: "not_after")', function() {
      // uncomment below and update the code to test the property notAfter
      //var instance = new WebsocketGateway.CertificateStatusDto();
      //expect(instance).to.be();
    });

    it('should have the property notBefore (base name: "not_before")', function() {
      // uncomment below and update the code to test the property notBefore
      //var instance = new WebsocketGateway.CertificateStatusDto();
      //expect(instance).to.be();
    });

    it('should have the property renewalTime (base name: "renewal_time")', function() {
      // uncomment below and update the code to test the property renewalTime
      //var instance = new WebsocketGateway.CertificateStatusDto();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "state")', function() {
      // uncomment below and update the code to test the property state
      //var instance = new WebsocketGateway.CertificateStatusDto();
      //expect(instance).to.be();
    });

    it('should have the property stateMessage (base name: "state_message")', function() {
      // uncomment below and update the code to test the property stateMessage
      //var instance = new WebsocketGateway.CertificateStatusDto();
      //expect(instance).to.be();
    });

  });

}));
