/**
 * websocket-gateway
 * Describe the weboscket endpoints
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WebsocketGateway);
  }
}(this, function(expect, WebsocketGateway) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WebsocketGateway.ContainerStatusDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ContainerStatusDto', function() {
    it('should create an instance of ContainerStatusDto', function() {
      // uncomment below and update the code to test ContainerStatusDto
      //var instance = new WebsocketGateway.ContainerStatusDto();
      //expect(instance).to.be.a(WebsocketGateway.ContainerStatusDto);
    });

    it('should have the property currentState (base name: "current_state")', function() {
      // uncomment below and update the code to test the property currentState
      //var instance = new WebsocketGateway.ContainerStatusDto();
      //expect(instance).to.be();
    });

    it('should have the property image (base name: "image")', function() {
      // uncomment below and update the code to test the property image
      //var instance = new WebsocketGateway.ContainerStatusDto();
      //expect(instance).to.be();
    });

    it('should have the property lastTerminatedState (base name: "last_terminated_state")', function() {
      // uncomment below and update the code to test the property lastTerminatedState
      //var instance = new WebsocketGateway.ContainerStatusDto();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new WebsocketGateway.ContainerStatusDto();
      //expect(instance).to.be();
    });

    it('should have the property restartCount (base name: "restart_count")', function() {
      // uncomment below and update the code to test the property restartCount
      //var instance = new WebsocketGateway.ContainerStatusDto();
      //expect(instance).to.be();
    });

  });

}));
