/**
 * websocket-gateway
 * Describe the weboscket endpoints
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WebsocketGateway);
  }
}(this, function(expect, WebsocketGateway) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WebsocketGateway.ContainerStateTerminatedDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ContainerStateTerminatedDto', function() {
    it('should create an instance of ContainerStateTerminatedDto', function() {
      // uncomment below and update the code to test ContainerStateTerminatedDto
      //var instance = new WebsocketGateway.ContainerStateTerminatedDto();
      //expect(instance).to.be.a(WebsocketGateway.ContainerStateTerminatedDto);
    });

    it('should have the property exitCode (base name: "exit_code")', function() {
      // uncomment below and update the code to test the property exitCode
      //var instance = new WebsocketGateway.ContainerStateTerminatedDto();
      //expect(instance).to.be();
    });

    it('should have the property exitCodeMessage (base name: "exit_code_message")', function() {
      // uncomment below and update the code to test the property exitCodeMessage
      //var instance = new WebsocketGateway.ContainerStateTerminatedDto();
      //expect(instance).to.be();
    });

    it('should have the property finishedAt (base name: "finished_at")', function() {
      // uncomment below and update the code to test the property finishedAt
      //var instance = new WebsocketGateway.ContainerStateTerminatedDto();
      //expect(instance).to.be();
    });

    it('should have the property message (base name: "message")', function() {
      // uncomment below and update the code to test the property message
      //var instance = new WebsocketGateway.ContainerStateTerminatedDto();
      //expect(instance).to.be();
    });

    it('should have the property reason (base name: "reason")', function() {
      // uncomment below and update the code to test the property reason
      //var instance = new WebsocketGateway.ContainerStateTerminatedDto();
      //expect(instance).to.be();
    });

    it('should have the property signal (base name: "signal")', function() {
      // uncomment below and update the code to test the property signal
      //var instance = new WebsocketGateway.ContainerStateTerminatedDto();
      //expect(instance).to.be();
    });

    it('should have the property startedAt (base name: "started_at")', function() {
      // uncomment below and update the code to test the property startedAt
      //var instance = new WebsocketGateway.ContainerStateTerminatedDto();
      //expect(instance).to.be();
    });

  });

}));
