/**
 * websocket-gateway
 * Describe the weboscket endpoints
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WebsocketGateway);
  }
}(this, function(expect, WebsocketGateway) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WebsocketGateway.NodeConditionDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('NodeConditionDto', function() {
    it('should create an instance of NodeConditionDto', function() {
      // uncomment below and update the code to test NodeConditionDto
      //var instance = new WebsocketGateway.NodeConditionDto();
      //expect(instance).to.be.a(WebsocketGateway.NodeConditionDto);
    });

    it('should have the property lastHeartbeatTime (base name: "last_heartbeat_time")', function() {
      // uncomment below and update the code to test the property lastHeartbeatTime
      //var instance = new WebsocketGateway.NodeConditionDto();
      //expect(instance).to.be();
    });

    it('should have the property lastTransitionTime (base name: "last_transition_time")', function() {
      // uncomment below and update the code to test the property lastTransitionTime
      //var instance = new WebsocketGateway.NodeConditionDto();
      //expect(instance).to.be();
    });

    it('should have the property message (base name: "message")', function() {
      // uncomment below and update the code to test the property message
      //var instance = new WebsocketGateway.NodeConditionDto();
      //expect(instance).to.be();
    });

    it('should have the property reason (base name: "reason")', function() {
      // uncomment below and update the code to test the property reason
      //var instance = new WebsocketGateway.NodeConditionDto();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new WebsocketGateway.NodeConditionDto();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new WebsocketGateway.NodeConditionDto();
      //expect(instance).to.be();
    });

  });

}));
