/**
 * websocket-gateway
 * Describe the weboscket endpoints
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WebsocketGateway);
  }
}(this, function(expect, WebsocketGateway) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WebsocketGateway.PodStatusDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PodStatusDto', function() {
    it('should create an instance of PodStatusDto', function() {
      // uncomment below and update the code to test PodStatusDto
      //var instance = new WebsocketGateway.PodStatusDto();
      //expect(instance).to.be.a(WebsocketGateway.PodStatusDto);
    });

    it('should have the property containers (base name: "containers")', function() {
      // uncomment below and update the code to test the property containers
      //var instance = new WebsocketGateway.PodStatusDto();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new WebsocketGateway.PodStatusDto();
      //expect(instance).to.be();
    });

    it('should have the property restartCount (base name: "restart_count")', function() {
      // uncomment below and update the code to test the property restartCount
      //var instance = new WebsocketGateway.PodStatusDto();
      //expect(instance).to.be();
    });

    it('should have the property serviceVersion (base name: "service_version")', function() {
      // uncomment below and update the code to test the property serviceVersion
      //var instance = new WebsocketGateway.PodStatusDto();
      //expect(instance).to.be();
    });

    it('should have the property startedAt (base name: "started_at")', function() {
      // uncomment below and update the code to test the property startedAt
      //var instance = new WebsocketGateway.PodStatusDto();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "state")', function() {
      // uncomment below and update the code to test the property state
      //var instance = new WebsocketGateway.PodStatusDto();
      //expect(instance).to.be();
    });

    it('should have the property stateMessage (base name: "state_message")', function() {
      // uncomment below and update the code to test the property stateMessage
      //var instance = new WebsocketGateway.PodStatusDto();
      //expect(instance).to.be();
    });

    it('should have the property stateReason (base name: "state_reason")', function() {
      // uncomment below and update the code to test the property stateReason
      //var instance = new WebsocketGateway.PodStatusDto();
      //expect(instance).to.be();
    });

  });

}));
