/**
 * websocket-gateway
 * Describe the weboscket endpoints
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WebsocketGateway);
  }
}(this, function(expect, WebsocketGateway) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WebsocketGateway.DeploymentApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DeploymentApi', function() {
    describe('handleDeploymentLogsRequest', function() {
      it('should call handleDeploymentLogsRequest successfully', function(done) {
        //uncomment below and update the code to test handleDeploymentLogsRequest
        //instance.handleDeploymentLogsRequest(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('handleDeploymentStatusRequest', function() {
      it('should call handleDeploymentStatusRequest successfully', function(done) {
        //uncomment below and update the code to test handleDeploymentStatusRequest
        //instance.handleDeploymentStatusRequest(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
